### ISSUE TITLE
Visual C++ 2015、2017、2019 再頒布可能ファイル

### ISSUE THREAD

**Issue by tfukumori** [seosoft/BfCompQnaBot#4]
有用なドキュメントありがとうございます。
開発環境構築含め、非常に参考になっております。

https://github.com/seosoft/BfCompQnaBot/blob/master/docs/01_install.md
上記ドキュメントで追記したほうが良いかもしれない事象がありましたのでご参考まで。

環境：Windows 10 Pro 20H2

新規の仮想環境で上記の環境で試したところ、Bot Framework ComposerがStarting Serverのままで起動しないことがありました。

調査したところ、以下のIssueにたどり着きました。
https://github.com/microsoft/BotFramework-Composer/issues/7964

最終的に、Issueに記載の次のVisual C++ 2015、2017、2019 再頒布可能ファイルをインストールすることで、Bot Framework Composerの正常起動と正常動作（既存のBotで確認）を確認しました。
https://aka.ms/vs/16/release/vc_redist.x64.exe

以上ご参考まで

**Comment by seosoft** [comment]
複数台のマシンで実施しましたが、この事象は見たことがなかったので助かりました。
追記しました。
情報ありがとうございます。
