### ISSUE TITLE
「開発環境の構築」ページでのBot Framework Composerのダウンロードリンクでは2.0.0がダウンロードされる

### ISSUE THREAD

**Issue by tfukumori** [seosoft/BfCompQnaBot#5]
[開発環境の構築](https://github.com/seosoft/BfCompQnaBot/blob/master/docs/01_install.md)ページでリンクされている次のリンクですが、記事冒頭の記載とは異なり、2.0.0がダウンロードされるようです。

<html>
<body>

OS | インストーラーのアドレス
-- | --
Windows | https://aka.ms/bf-composer-download-win
macOS | https://aka.ms/bf-composer-download-mac
Linux | https://aka.ms/bf-composer-download-linux

</body>
</html>

もちろんMicrosoft側の問題であり、留意の上ダウンロード、またはバージョンアップすればよい想定のお話とは承知しておりますが、念のため報告いたします。
（[GitHubのRelease](https://github.com/microsoft/BotFramework-Composer/releases/tag/v2.1.0)からのダウンロードというのはリンク切れなどを考慮するとあまり望ましくないですよね……）

**Comment by seosoft** [comment]
以下の理由から改訂はしないものとします。

- 状況の変更に対応しなければ困る差異ではなく、やって見れば分かるというレベルである
- Bot Framework Composerは現在はその役目を果たし終えたと考えられ、参考にする以外に今後このリポジトリを利用することは考えづらいため（とはいえ、もしものためにリポジトリをアーカイブにはしていません）
- そもそもこの後の手順 (QnA Maker) は実施できなくなってしまった

Power Virtual Agents版の手順を作れば済む話ではあるのですが、現状では作成予定はありません。
